### ISSUE TITLE
Readium-2 project name creating confusion

### ISSUE THREAD

**Issue by BluefireMicah** [readium/readium-2#30] opened 2017-03-15 16:05 UTC
This is a continuation of a conversation started in issue: https://github.com/readium/readium-2/issues/26 "Define a roadmap for Readium-2".  The thrust is that some community members (myself included) feel that the Readium 2 label has become confusing and problematic due to the fact that it is not, strictly speaking, version increments of current projects, rather new projects that tackle similar functionality/use cases as those of existing projects, but with different technical architectures, goal sets, assumptions, development methodologies, and scope. e.g. apples and oranges vs the more traditional version upgrade/update conventions using numerical progression.  

It seems to me that there are basic two sub-topics here:

1. There is currently no general consensus that the name should be changed. So this is a thread where various contributors can express their support of the change, and reasoning. Whereas others can express their opposition to the change and reasoning for that opposition.  Ideally we will reach general consensus, however, if that is not possible to achieve it can be elevated to the Readium Board for consideration and vote.

2. If we are to adopt a new naming convention for communicating intent more clearly, and for organizing discreet modules into logical groupings, what should that new convention be?

Any and all input is much appreciated. I think this is an important issue and I will do my best to keep the conversation moving forward productively.

**Comment by BluefireMicah** [comment] 2017-03-15 16:07
FYI, I have laid out my arguments fairly extensively in the genesis issue (Define a roadmap for Readium-2). If folks feel I should move/repeat that here in this thread, let me know.
-Thanks

**Comment by HadrienGardeur** [comment] 2017-03-15 19:06
I'm strongly against the idea of renaming a project for which we've already been doing presentations for the last few months.

The name was already changed once (from "Readium Next" to "Readium-2", a name which you've already approved @BluefireMicah) and I don't see how this will help us move forward at all.

Instead, I believe that we should make a better effort at explaining what Readium-2 is and isn't, communicating about its current status and providing different means to keep track of the project.

I'd also like to point out that "Readium-1" never did that kind of effort, in fact Readium-1/Readium SDK is as vague as the first EPUB specification (for which there was no single document but instead three separate specifications, none of them called EPUB).

Compared to that project, Readium-2 is already more organized. There's a single repo where we:

- provide links to every active project under the Readium-2 umbrella
- have a single issue tracker where we can discuss project-wide issues
- document each module (we'll also store tests for each module very soon)
- and now any member of this organization also has access to a project board

We'll continue to discuss and improve how we can be even more transparent in the future, that's IMO what could really make a difference.

**Comment by BluefireMicah** [comment] 2017-03-15 19:07
FYI, Please make sure to read through Issue 26 before posting here, at least up to the point where we split the conversation into this separate issue. Thanks!
-Micah

**Comment by BluefireMicah** [comment] 2017-03-15 19:14
@HadrienGardeur I like what you are doing in terms of efforts to improve transparency and communication from prior approaches. Thank you for that!  If I understand your comment, your "reason for opposition"to the name change is that you have done presentations previously that referred to the 'old" name? I can understand that this is non-ideal, but It does not seem to be that this outweighs the negatives we are seeing with the current name. I would thus assume that you don't see the current negatives in the same way I do. I will atttempt to make that clearer. I think @jasonmerry did a fairly good job of expressing that, and I expect to gather a dozen or so more "testimonials" along these lines to help illustrate my concerns.

**Comment by jmgeffroy** [comment] 2017-03-15 21:56
Jumping for a few minutes into this thread from my current retirement in paradise. Just to confirm the issues the Readium 2 name has created. I've been struggling myself with that when talking to many people, including prospects and "partners" whatever that means). I would personally prefer something like "Readium Elements" or "Readium Particles". Or anything that conveys the idea of modularization. Errare humanum est, perseverare diabolicum perfectly applies there ;-)

**Comment by rkwright** [comment] 2017-03-15 23:19
++ Totally agree.  I was the one that initially labeled the idea of a new "iteration" of Readium as "Readium Next" but a number of people felt that was misleading.  Instead, after some discussion we agreed on "Readium 2" as a label.   But at the time, it was viewed as likely to be a _refactoring_ of Readium 1.  After much discussion, we realized that this was going to be a) a very large amount of work and b) didn't align with the desires of those who wished to do the work.  So it was decided to start fresh and develop a new set of "modules" that would be developed on a per-platform basis.  I have no problem with this - on the contrary, I still think it is a great idea and support its development.  BUT, calling it "Readium-2" suggests that it is a natural and organic successor to Readium-1, which, IMHO,  it is clearly not.  The current set of modules we are calling Readium-2 is not and in all likelihood will never be a "replacement" for "Readium 1".

We currently have, in Readium 1:

- Readium SDK - the native code set of libraries that can be built into native applications
- ReadiumJS - the pure JavaScript set of libraries (which shares readium-shared-js and readium-cfi-js with the SDK) which forms the basis of the Chrome application (nee Extension) and the CloudReader

These provide the basis for native iOS and Android applications and Chrome and cross-browser applications.  The current "Readium-2" on the other hand, is a collection of modules which ultimately may be leveraged to provide various ways of opening and displaying EPUB/PWP content in various ways.  But they are, by design, highly modular and intended to be mixed and matched however the developer intended to use them.  Not so much as a SDK or full-fledged application as building blocks.  Which is great, but not at all the design goal or usage of Readium 1.

So it seems misleading, as the label "Readium-2" suggests, that they are a _replacement_ for Readium 1.  And it is clear, from conversations with Readium Foundation members, clients and customers, that this message is not getting across.  Given that the timeframe for rolling out complete, tested modules for R2 will be (if the current momentum can be maintained) will be Q4 2017, it is going to be a long period of explanations.

Better, IMHO, to correct our mistake now and rename the larger effort now termed "Readium 2" as something aligned with its intent, which is to support both EPUB and PWP. Indeed, if we see (as some do) that PWP might encompass EPUB over time, then R2 could be seen as a PWP viewer.  Indeed, there have been some conversations about how the R2 work could play into the PWP effort.

Net net, I think we should rethink the "Readium 2" label and rename it to be more aligned with what it is, which is a broader effort aimed at EPUB3/4 and PWP management/rendering.

**Comment by HadrienGardeur** [comment] 2017-03-15 23:53
Some good points in there about WP/PWP Ric, but it's hard to say when this W3C spec will be ready, so I wouldn't tie R2 to it.

>The current set of modules we are calling Readium-2 is not and in all likelihood will never be a "replacement" for "Readium 1".
>
>We currently have, in Readium 1:
>Readium SDK - the native code set of libraries that can be built into native applications
>ReadiumJS - the pure JavaScript set of libraries (which shares readium-shared-js and readium-cfi-js with the SDK) which forms the basis of the Chrome application (nee Extension) and the CloudReader

Sorry but that part is simply not true.

The streamer in R2 is EXACTLY a replacement for Core SDK, there's nothing that Core SDK did that won't be handled by the streamer. It's even fairly easy to make the R2 streamer compatible with the R1 APIs if we want to.

Same thing for the navigator modules, a number of them could fully replace ReadiumJS.
It's also worth pointing out that there's nothing in the current architecture that would stop us from making ReadiumJS compatible with the R2 navigator architecture (Evident Point made that point very early on).

So while people can argue that they like the name "Readium Fairy Dust" better than "Readium 2", the whole "it won't replace Readium 1" perspective is plain wrong.
While SharedJS may coexist peacefully with other navigator implementations, there are very little reasons to keep using Core SDK aside from pre-existing DRM implementations (that could also be ported to R2).

**Comment by BluefireMicah** [comment] 2017-03-16 01:28
Could and will are different things, and pre-existing DRM implementations are not a trivial consideration. But, in any case, functionality and adoption are the key, and naming conventions are just that. Right now it is creating problems and is confusing. In the future, it COULD no longer be. But why wait and see, when we can fix it now?

**Comment by BluefireMicah** [comment] 2017-03-16 01:30
That is, I still do not see a compelling reason *not* to address the issue that many of us see right now.

**Comment by HadrienGardeur** [comment] 2017-03-16 01:31
For the streamer it is neither "could" or "will", the Go version already supports every feature currently available in Core SDK.

**Comment by BluefireMicah** [comment] 2017-03-16 01:36
So, I could say, swap it out in my current iOS and Android app projects today, and release updates next week with same functionality?

**Comment by HadrienGardeur** [comment] 2017-03-16 01:38
It's a possibility. The only missing piece would be to serialize the in-memory model to a different JSON document, which is trivial in Go.

**Comment by BluefireMicah** [comment] 2017-03-16 01:43
So you are claiming that it is a logical upgrade/update for Readium SDK implmenters with current apps on the market, and is ready now, with some very minor tweaks? Any potential reasons why someone would not adopt?

**Comment by BluefireMicah** [comment] 2017-03-16 01:44
e.g. when you say "it is a possibility"do you mean you would expect that I would and should?

**Comment by HadrienGardeur** [comment] 2017-03-16 01:46
I'm saying that the Go version is at a point where it's feature complete and could replace Core SDK, yes.

To get the full benefits in terms of ease of integration (fully native code) and ability to work with the in-memory model created by the streamer (something that you don't easily have access to with Core SDK), you're better off waiting for the Swift/Java port to reach that same stage.

**Comment by BluefireMicah** [comment] 2017-03-16 02:06
That is not the understanding that I've been under. I think we should get a few of the app implementer tech leads to huddle  (e.g. Bluefire, Mantano, Evident Point, others) and see if I was misinformed and there is in fact consensus that Streamer is clearly the logical near future update path, and assess how far out in time that is (and of course, the DRM modules are an important component of that).

**Comment by BluefireMicah** [comment] 2017-03-16 04:33
I will need to largely step away from this conversation for a while as I'm traveling through end of next week. I will say this. It is clear to me @HadrienGardeur that you understand the nature of my concerns, and yet you continue to be firm in your resistance. So, I can only assume that you feel strongly about this (for reasons I don't quite understand yet). But I see that and respect it. And, to be clear of my intentions, moving forward, I would not be in favor of the name change unless you agree.

**Comment by rkwright** [comment] 2017-03-16 13:43
I am sure that one COULD potentially replace the SDK with the Go Streamer, but I suspect there would be a LOT of little gotchas to work around  AND there would then need to be a ton of testing and so on.  But ultimately the question to me would be, why would you do that?  What is the value proposition?  The native Readium SDK stack already works - as witness mature, performant implementations such as Bookari (Mantano) and CloudShelf (Bluefire).   Why invest all that time and money to replicate existing functionality?  The "Readium 2" effort isn't, IMO, an attempt to replicate what R1 already does.  It's exploring a more modular approach that can be used for both EPUB and PWP and other possibilities we haven't yet explored.  But "Readium 2" isn't there yet and has a long way to go (though the progress so far is excellent).

So calling it "Readium 2" is to my mind misleading and confusing to our customers and members.  I really think we to find another name for it as soon as possible.

**Comment by HadrienGardeur** [comment] 2017-03-16 14:09
The maturity of Core SDK depends to a large extent on the platform that you're targeting. 

If you want to build a Windows application for example, it might be a lot less work to start from the Readium-2 streamer than to use Core SDK.

You also asked for specific reasons why it might make more sense to use the R2 streamer instead of the Core SDK, let me list a few of them:

- better support for metadata (including 3.1 support)
- better APIs for media overlay
- the ability to introduce new formats such as audiobooks or comics
- better use of HTTP caching and link relationships (with a Chromeview and Electron, you could get prerendering for free that way)
- the ability to quickly add new APIs in there (search for instance, which is currently missing from Core SDK)
- it's much easier to get your hands dirty and change something in the streamer

There's also a big difference between companies that have already implemented R1 and released products, and those that are planning to use Readium in the near future. 
If you're planning to release a Windows app with search and LCP support (just to give one example), it makes perfect sense to consider the R2 streamer over Core SDK.

**Comment by rkwright** [comment] 2017-03-16 14:33
I would agree with this if a company is just starting out and isn't in a hurry (like getting a product out in 2017) then starting with the Go Streamer makes sense, but if I am going to do that, why use even part of R1?  Why not join the R2 effort and work to get it to fruition?  Of course, if you need to support ACS and URMS DRMs then there are other issues.

**Comment by HadrienGardeur** [comment] 2017-03-16 14:44
If you need to support ACS, Readium is the last of your concern ;-)

For a product shipping in 2017, I disagree, it will definitely be possible to use the streamer this year.

I also agree that in this case, you should be part of the R2 effort, but the beauty of the modular design is that you can use whatever you want.

If you want to ship an app based on the R2 Go streamer on the server side and Shared JS in a desktop Electron app, you can do that.
If you want to have the Go streamer locally and another navigator (let's say EPUB.js), well you can do that too.

Being modular and replacing R1 building blocks are not mutually exclusive.

**Comment by llemeurfr** [comment] 2017-03-16 15:05
I'll re-express my position here, which is that Readium 2 is a project name chosen some months ago and presented to the public several time with this name (incl. at the EPUB Summit last week). 

At a human level, its objectives are to satisfy a community which is not happy with the SDK as it is. 
At a functional level, its objectives are the same as Readium SDK (incl. shared JS) = a "reading engine".  But it's a different way to achieve this goal, and people working on this are expecting better performances, better documentation, better ease of maintenance and evolutions, better modularization + what @HadrienGardeur has put forward. Therefore the "2" token has a logic. 

This naming thread mainly involves companies which make their life of selling Readium SDK based products (both of them having largely forked from the Readium code to get it running fast).
I understand that the "Readium 2" token can be problematic for Bluefire and Mantano: it's as if their software was made obsolete by the new kid in town. It's a wrong impression, but people don't always understand the details. 

It would be good to also have the position of people involved in the two projects (pls don't take it badly, but BlueFire and Mantano have been involved in Readium SDK, not in R2 so far).

**Comment by BluefireMicah** [comment] 2017-03-16 15:28
I agree with the facts as stated, except for the assertion that we have forked from the Readium code base in our own implementations. This is simply factually incorrect.

**Comment by bluefirepatrick** [comment] 2017-03-16 15:52
Hello all, intersting discussion!  I have a few questions about the streamer.

1) With regard to performance, is there a benchmark test for Android and iOS that I could look at that demonstrates a better performance for the streamer vs the ePub3 SDK Library? 

2) Also, I am curious how the ContentFilter module of Readium SDK 1 would work in the streamer.  How, for instance, is it handling obfuscated fonts at present?  Also the ContentFilter pattern is essential for DRM at present.  What is the streamer plan for allowing for in-memory decryption for projects like LCP, and other book DRM system?

3) Also, I am a little confused on the 'goodbye JNI' front, as far as I understand using Go on something like Android, you either need to write a Go library to generate language bindings for Java and Objective-C (which seems JNI-like) or write an app entirely in Go (which I think could be problematic in you wanted to also use Java or the NDK for other modules within your Android App). Do I have that wrong?  And is the plan to create language bindings or rely on entirely Go-based Android apps?

I am not a 'Go on Android' expert so TIA for any help here.

**Comment by jce1028** [comment] 2017-03-16 15:56
Again, I think the issue in naming is leaving the implied intent undefined.  I think we simply need to state the two different projects as such.  Two different approaches to doing the same thing instead of letting people assume one is the "next" evolution. They are just simply different approaches that serve an implementors development needs.  I think we are arguing over a name because we have not defined the defining what them on the web site as Option A or Option b..  I say little b because it (R2) is incomplete.  So folks can make there choice between current options.  Changing a name is not going to change someone's assumption of what the new option is.  We use Option 1 today and will likely adopt components of Option 2 in the future for our unique needs and frankly, engineering approach and preference.  Plus I am loathe to re-open what I consider a closed issue.    What I am for is encouraging Readium Management to revisit how the web describes the two options so we help those in the community that are being negatively impacted by the lack of proper marketing.  

Respectfully, James.

**Comment by HadrienGardeur** [comment] 2017-03-16 16:15
Hello @bluefirepatrick 

The Go implementation is simply the most mature of the three versions currently in development (the other two being Swift and Java).

To answer your questions:

1. On Android & iOS, you would probably use the Java and Swift versions instead. 
I haven't benchmarked the Go version vs Core SDK yet, but on a MacBook Air from 2013, LCP protected resources (HTML, CSS) are served in HTTP in roughly 1-5ms, with larger resources such as fonts taking anywhere between 10-25ms.
Since most of these resources can also be pre-fetched or even pre-rendered in some cases, it should be blazing fast for the end user. For unencrypted resources, the requests are usually sub 1ms.
2. There's an equivalent pattern in the streamer called the fetcher, which is responsible for handling decryption of both fonts and LCP right now. Each resource has four info potentially associated to it (algorithm, DRM scheme, DRM profile and original size) that the fetcher can use to properly decrypt these resources.
For LCP, Go has built-in support for AES with hardware optimizations (that's how Cloudflare handles all of its traffic for example).
3. It's goodbye JNI because on Android you would use the Java port of the streamer, which means that you'll have direct access to the in-memory model and all the objects/methods exposed by the streamer.

If you want to have a longer discussion about this, I would advise opening up a new issue on this repo, this will avoid forking the discussions here.

**Comment by bluefirepatrick** [comment] 2017-03-16 16:41
Thanks, Hadrien.

I believe that identifying that replacing Readium 1 will rely on Java and Swift ports of The Go Streamer is directly applicable to this discussion.  Benchmarking too.  Without understanding the details of the plan it is hard for me to make any determinations about the statements being made in this thread.

**Comment by BluefireMicah** [comment] 2017-03-16 16:43
@llemeurfr I have already myself explicitly stated that:
1. Bluefire and companies like it are uniquely impacted by this problem
2. Bluefire supports the new initiatives, is excited about  them, and is appreciative of the contributions by our peers and have said so publicly, including in this very thread. We have in fact been involved in multople meetings and discussions with our peers who are actively involved in these projects. While it is "alternative facts" that we have forked Readium SDK in our projects, it is an actual fact that we have not yet contributed code to Streamer or Navigator, but then as Hadrien previously mentioned in this very thread, Feedbooks has contributed 100% of the code so far, and thus we are not particularly unique in that regard among the Readium community.

And while the problem does uniquely impact companies like mine, clearly the issue is broader than that (based on what I've heard from other potential adopters, what we heard on this thread from one, and what Ric has heard and observed, and in my conversations with other Board members including Bill McCoy). Half of the individuals (4) that have posted here so far in this first foray into a "public"conversation expressing favoring a change, have been non-implementers. 

I have already stated my intent that I would not support changing the name without @HadrienGardeur 's explicit consent, and this is due to the great respect I have for his previous and ongoing contributions to this overall project and organization as a whole.

I also appreciate EDRL and your own contributions to the projects, and I admire the fact that there are aspirations to continually improve the process, documentation, and quality of these community projects.

**Comment by HadrienGardeur** [comment] 2017-03-16 16:55
> [...] but then as Hadrien previously mentioned in this very thread, Feedbooks has contributed 100% of the code so far, and thus we are not particularly unique in that regard among the Readium community

Only for the Go version, which is leading the way for the streamer.

The Swift version has code from both Olivier (ABM) and Alexandre (EDRLab). The Java version was started by contributors that are not even Readium members but liked the architecture and ideas, they now want to contribute this project back to Readium under a BSD license and work together with the rest of this community (which is super cool).

**Comment by winniequinn** [comment] 2017-03-16 19:32
On Mar 15, 2017, at 7:19 PM, Ric Wright wrote:

> The current "Readium-2" on the other hand, is a collection of modules which ultimately may be leveraged to provide various ways of opening and displaying EPUB/PWP content in various ways. But they are, by design, highly modular and intended to be mixed and matched however the developer intended to use them. Not so much as a SDK or full-fledged application as building blocks.

I would like to voice my concern about this description. My understanding is that we're developing interchangable bits and pieces now because that's just a good way to do development, but I think it would be a shame if we could not offer a proper SDK to web and mobile developers at some point in the future. After all, some of our biggest issues with Readium 1 are the ad hoc nature of it and the fact that so much application code and domain knowledge is necessary to glue everything together!

> So it seems misleading, as the label "Readium-2" suggests, that they are a replacement for Readium 1.  And it is clear, from conversations with Readium Foundation members, clients and customers, that this message is not getting across. 

I am not sure any other name is going to improve this so much. Whether we call it Readium 2 or Readium Next or Readium Particles or what have you, people are still going to hear New Readium Thing and are going to assume it's somehow replacing or improving upon what already exists.

I am not sure this is a bad thing either! NYPL is interested in being involved in this project precisely because we see it as an improvement and, eventually, a replacement. It seems reasonable to me that, some years from now, Readium 2 will be something that application developers can drop into their projects and have a basic working reader. It also seems reasonable to be that support for Readium 1 will not continue indefinitely given all of the technical debt the project has accrued.

> Net net, I think we should rethink the "Readium 2" label and rename it to be more aligned with what it is, which is a broader effort aimed at EPUB3/4 and PWP management/rendering.

Perhaps it's because we at NYPL are so focused on replacing Readium 1 as Micah pointed out, but I do think that positioning R2 strictly as "the EPUB 3.x, 4.x, and PWP thing" is not necessarily the best way to go. After all, our goal with R2 is have a stable, performant, accessible, and maintainable EPUB 2.x and 3.x rendering option. I understand others contributing to the project have broader goals in the nearer term than we do and that's great, of course! At the same time though, I think it would a shame to pitch R2 as something primarily for the possible problems of tomorrow when there's a lot of focus on making it an excellent solution for the problems of today.

Disclaimer: These opinions are mine and mine alone!

**Comment by AlanQuatermain** [comment] 2017-03-16 19:56
It may be worth looking at the model of libraries like libxml, where you can choose to build the library with or without any number of significant pieces via build flags. These are still modular, and implementors can pick and choose which to include at compile time, but the output is still very much a library with an SDK.

Apologies for brevity, I'm typing this with all thumbs.

**Comment by BluefireMicah** [comment] 2017-03-16 20:04
However we communicate to the community about the collection of new projects in terms of goals, aspirations, target platforms, functionality, and use cases - and naming conventions, I'm confident that this can be done in a positive and productive way across the board that:
1. Attracts new contributors, creates excitement and engagement, challenges existing assumptions, learns from the past and forges new ground.   While also:
2. promotes the adoption of current, ready to use code libraries, that honors and celebrates the contributions made and the value created by contributors and adopters, and that empowers and energizes prior contributors and adopters.  A

And, it can all be done in with honesty, clarity and transparency about the nature of the existing and new projects, their current "real" status, and pros of cons when considering adoption of, or contributions to, various projects that might serve similar functions.  

Of course, we've all seen the pattern over and over in software that the folks that did all the hard work are proud of their accomplishments and want recognition, want to benefit from that hard work, and want their work to be appreciated for the good things about it, and not focus on the bad.

Newcomers always look at existing code they did not write, and find it lacking and are certain that they can and will do better than their predecessors via a full rewrite.  Sometimes they succeed. Often times they do not.

This is such a classic pattern that approaches archetypal dimensions. This does not mean either perspective is right or wrong, rather, just predictable.   

I feel passionately that we collectively do not need to throw community members, contributors, implementers or projects "under the bus" in order to justify work on new things. Nor does denigrating each or discrediting each other serve any of us.  I myself feel that Bluefire and projects that we've worked hard on have and are being thrown under a bus at times, and it sucks pretty hard. I truly believe we can all support each other, and our shared mission, and I think we should. I'm committed to doing that, and I hope others share that commitment.

**Comment by winniequinn** [comment] 2017-03-16 20:28
[AlanQuatermain wrote](https://github.com/readium/readium-2/issues/30#issuecomment-287173114):

> It may be worth looking at the model of libraries like libxml, where you can choose to build the library with or without any number of significant pieces via build flags. These are still modular, and implementors can pick and choose which to include at compile time, but the output is still very much a library with an SDK.

I am okay with appropriate use of run-time configuration, but I would very much like to avoid the use of conditional compilation as much as possible. It makes it difficult to understand all of the possible interactions between parts of the code, makes testing difficult, confounds IDEs, et cetera.

Instead, I'd much rather build a set of interfaces and let users of a given library provide an implementation of a given interface or not as they see fit. I think this is the path we're already headed down at the moment.

**Comment by BluefireMicah** [comment] 2017-03-17 03:25
@HadrienGardeur I'm looking for the Swift Streamer code in github that you mention above, but not seeing it. Can you point me to it?

**Comment by llemeurfr** [comment] 2017-03-17 13:54
@BluefireMicah be sure that EDRLab is committed to support Readium 1 in front of its members, some of them (Mantano, but also ABM, Jouve, Immanens, Prismallia ...) having spent quite a lot of time taming the SDK and being fine with it. It's not about pushing one solution against the other, it's acknowledging that alternatives approaches are possible inside the same broad community. 
It's much better to has both approaches branded "Readium" rather than seing a bunch of developers creating "something else" "elsewhere".

**Comment by HadrienGardeur** [comment] 2017-03-17 14:06
To go back to the whole "Readium-2 is for WP/PWP & EPUB 4" thing, I'd just like to point out that there's now a first draft of a timeline for W3C deliverables: https://rawgit.com/w3c/dpubwg-charter/schedule-draft/index.html#timeline

As you can see, while the DPUB WG expect to have a first public draft at the end of the year for WP/PWP, there won't be one available before Q1 2018 for EPUB 4.
Candidate recommendations (when things start getting stable spec-wise) won't be available before Q4 2018.

Readium-2 has a very different timeline as the Go version of the streamer has already reached the Feature Complete Requirements stage, and we expect to have all three implementations at a rev 1/rev 2 stage this summer.
For the project overall, the target is definitely to have all modules in a good shape by the end of the year.

This is a very different timeline from the DPUB WG, and while Readium-2 can play a role in WP/PWP/EPUB 4 adoption, it'll be ready and useful for implementers at least a year before the DPUB WG has a first Candidate Recommendation.

**Comment by iherman** [comment] 2017-03-17 14:15
@HadrienGardeur this is just a very preliminary timeline that I came up with yesterday for the discussion on Monday. I am usually very pessimistic in my planning, and take [Hofstadter’s law](https://en.wikipedia.org/wiki/Hofstadter's_law) very much into account when planning:-) So do not take this as cast in concrete; this is to be discussed on Monday. If the timeline can be shorter, I am the first one to be happy. Please try to be on the call or Monday and/or comment on the current text, possibly providing comments.

I.

P.S. Nevertheless, in my experience, the reviews on privacy, security, internationalization, and accessibility (to take only those reviews that are obligatory in a W3C process) do take some time, which we should not underestimate. The other big chunk of time is the requirement of a thorough testing and comprehensive test suite.

**Comment by HadrienGardeur** [comment] 2017-03-17 17:23
Thanks @iherman for these additional info and I'll def attend the call on Monday.

That said, I still believe that my point stands. Even if all goes well for WP/PWP/EPUB4 and they're actually ready 6 months before (which means late Q2/Q3 2018), this is still a good 6 to 12 months difference compared to the current timeline for Readium-2:

- all streamer implementations at rev1/rev2 stage this summer
- navigator at a similar stage by the end of the year

While it is our goal to experiment WP/PWP/EPUB4 as soon as we can in the streamer (I don't expect these works to affect the navigator much), adoption for these new formats is not at the core of our work on Readium-2 for the next 9 months at least.
We're exploring concepts and technologies that could play a role in WP/PWP/EPUB4, but with EPUB 2.x and 3.x in mind for now.

**Comment by llemeurfr** [comment] 2017-03-17 17:37
@HadrienGardeur I'll just replace the "could play a role" by a "will play a role".

**Comment by HadrienGardeur** [comment] 2017-03-17 17:44
@llemeurfr I certainly hope so, but I don't know how much the W3C DPUB WG will appreciate our work on the Readium Web Publication Manifest and the streamer.

**Comment by dauwhe** [comment] 2017-03-17 17:47
>I certainly hope so, but I don't know how much the W3C DPUB WG will appreciate our work on the Readium Web Publication Manifest and the streamer.

@HadrienGardeur I can't speak for the whole group, but I think it's great. In the spirit of the extensible web manifest, we can't make a good spec without experiments and implementations. We do ask that you provide as much feedback to the working group as possible.

**Comment by iherman** [comment] 2017-03-17 18:23
> On 17 Mar 2017, at 18:47, Dave Cramer <notifications@github.com> wrote:
> 
> I certainly hope so, but I don't know how much the W3C DPUB WG will appreciate our work on the Readium Web Publication Manifest and the streamer.
> 
> @HadrienGardeur I can't speak for the whole group, but I think it's great. In the spirit of the extensible web manifest, we can't make a good spec without experiments and implementations. We do ask that you provide as much feedback to the working group as possible.
> 

+1

**Comment by iherman** [comment] 2017-03-18 08:41
Hi @HadrienGardeur

>While it is our goal to experiment WP/PWP/EPUB4 as soon as we can in the streamer (I don't expect these works to affect the navigator much), adoption for these new formats is not at the core of our work on Readium-2 for the next 9 months at least. We're exploring concepts and technologies that could play a role in WP/PWP/EPUB4, but with EPUB 2.x and 3.x in mind for now.

I would propose to leave this a bit open for now, until the WG starts. Obviously, I talk in the name of the prospective WG: as we also discussed with @llemeurfr, having some sort of a “reference implementation” for PW/PWP/EPUB4 would be, obviously, extremely important for the Working Group. Obviously, we will have to find a way to do this in a way that works for both organizations but, as I said, it seems to be too early to discuss the details now...

**Closed** 2017-09-05 15:07 UTC
Labels: Discussion
